### ISSUE TITLE
Feature Request: filter by project root

### ISSUE THREAD

**Issue by YodaEmbedding** [nvim-telescope/telescope-frecency.nvim#16] opened 2021-04-10 09:58 UTC
Let's say I have a couple of projects:

```
project_a
project_b
project_c
```

If I navigate inside a particular root directory, I would like frecency results only from within that project.

```bash
$ cd project_a
$ nvim

:Telescope frecency
project_a/main.py
project_a/i_love_opening_this_file.py
```

Project root can be determined by the presence of `.git` or `.svn`.

**Comment by teto** [comment] 2021-04-27 10:01
you can filter by cwd since https://github.com/nvim-telescope/telescope-frecency.nvim/issues/14 but to achieve what you want (this is what I want too), we should be able to default to `:CWD:` as a filter. I am not sure yet if that's possible with telescope (have a default query).

**Comment by Conni2461** [comment] 2021-04-27 12:04
There is a `default_text` option (sunjon asked me about that) but that one is currently broken because of missing missing prompt buffer patches in neovim. I have a workaround for that in https://github.com/nvim-telescope/telescope.nvim/pull/521 that will be merge soon. After that `:Telescope frecency frecency default_text=:CWD:` will do what you are looking for :)

**Comment by sandangel** [comment] 2021-06-18 15:45
hi, is there any update on this issue? I saw the PR is having merge conflicts. :(

**Comment by Conni2461** [comment] 2021-07-10 08:10
The PR is merged, this does now work `:Telescope frecency frecency default_text=:CWD:` but only the first time, the second time @sunjon s `persistent_filter` option kicks in https://github.com/nvim-telescope/telescope-frecency.nvim/blob/721300e3d6f4a7157a781014d3d69bb1c7b702a3/lua/telescope/_extensions/frecency.lua#L254

You would need to disable it or sunjon needs to check that `default_text` isn't already a tag.

To disable
```lua
telescope.setup {
  extensions = {
    frecency = {
      persistent_filter = false, ------ its this one
      show_scores = false,
      show_unindexed = true,
      ignore_patterns = {"*.git/*", "*/tmp/*"},
      workspaces = {
        ["conf"]    = "/home/my_username/.config",
        ["data"]    = "/home/my_username/.local/share",
        ["project"] = "/home/my_username/projects",
        ["wiki"]    = "/home/my_username/wiki"
      }
    }
  },
}
```

**Comment by Conni2461** [comment] 2021-07-10 08:12
I should probably also mention that you can do this with any other tag

`:Telescope frecency frecency default_text=:project:`

**Comment by sunjon** [comment] 2021-08-04 07:40
I've deprecated the `persistent_filter` option, as it was undocumented anyway.
The functionality can be reproduced with the above mentioned `default_text` and/or the upcoming
[cache/resume](https://github.com/nvim-telescope/telescope.nvim/pull/1051) PR.

**Closed by sunjon** 2021-08-04 07:40 UTC

**Comment by younger-1** [comment] 2021-09-21 04:50
> 
> 
> I should probably also mention that you can do this with any other tag
> 
> `:Telescope frecency frecency default_text=:project:`

`:Telescope frecency default_text=:project:` also works. So how is this different from `:Telescope frecency frecency default_text=:project:` internally as it only one `frecency`
